import Image from "next/image";
import Link from "next/link";
import { ProductCard } from "@/components/catalog/product-card";
import { Container } from "@/components/layout/container";
import { PublicShell } from "@/components/layout/public-shell";
import { categories, products } from "@/content/catalog";

export default function HomePage() {
  return <PublicShell>
    <div className="industrial-page">
      <section className="industrial-hero"><Container className="grid min-h-[40rem] gap-8 py-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:py-16"><div className="relative z-10"><p className="eyebrow-red text-xs font-bold tracking-[.18em]">LSQ XH · CONEXÕES PARA FLUIDOS</p><h1 className="mt-5 max-w-xl text-5xl font-semibold leading-[.98] tracking-[-.06em] md:text-7xl">Soluções em conexões <span className="text-signal-red">hidráulicas</span> para sua operação.</h1><p className="mt-6 max-w-lg text-base leading-7 text-white/70">Explore séries de engates e componentes LSQ. Consulte o catálogo técnico e encontre o canal comercial adequado para sua demanda.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="signal-button" href="/produtos">Ver produtos <span aria-hidden="true">→</span></Link><Link className="outline-button" href="/contato">Falar com especialista</Link></div></div><div className="industrial-surface relative min-h-[22rem] overflow-hidden lg:min-h-[33rem]"><div className="absolute inset-y-0 right-0 w-2/3 bg-signal-red/15" /><Image alt="Engate rápido hidráulico LSQ" className="object-contain p-8 drop-shadow-[0_2rem_2.5rem_rgba(0,0,0,.5)] lg:p-14" fill priority sizes="(min-width: 1024px) 55vw, 95vw" src="/products/lsq-ff.webp" /><p className="absolute bottom-5 left-5 border-l-2 border-signal-red pl-3 text-xs font-semibold tracking-[.13em] text-white/65">PRODUTO EM DESTAQUE · LSQ-FF</p></div></Container></section>
      <section className="border-y border-white/10 bg-[#15181b]"><Container className="grid divide-y divide-white/10 py-3 sm:grid-cols-3 sm:divide-x sm:divide-y-0"><p className="py-3 text-sm font-semibold text-white/75">Catálogo técnico por famílias</p><p className="py-3 text-sm font-semibold text-white/75 sm:px-6">Atendimento por WhatsApp e telefone</p><p className="py-3 text-sm font-semibold text-white/75 sm:px-6">Experiência 360 preservada</p></Container></section>
      <section><Container className="py-16 md:py-24"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow-red text-xs font-bold tracking-[.16em]">FAMÍLIAS DE PRODUTOS</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] md:text-5xl">Comece pela família certa.</h2></div><Link className="text-sm font-semibold text-white hover:text-red-300" href="/produtos">Ver catálogo completo →</Link></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.map((category, index) => <Link className="industrial-surface group min-h-52 p-6 transition-colors hover:border-signal-red" href="/produtos" key={category.slug}><p className="text-xs font-bold tracking-[.14em] text-white/40">0{index + 1}</p><h3 className="mt-12 text-xl font-semibold">{category.label}</h3><p className="mt-3 text-sm leading-6 text-white/60">{category.description}</p><span className="mt-5 inline-block text-sm font-semibold text-red-300 group-hover:text-white">Consultar família →</span></Link>)}</div></Container></section>
      <section className="border-y border-white/10 bg-[#15181b]"><Container className="grid gap-8 py-14 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div className="relative min-h-64 overflow-hidden border border-white/10 bg-[#0d0f11]"><Image alt="Componente industrial LSQ" className="object-contain p-8 opacity-80" fill sizes="(min-width: 1024px) 55vw, 95vw" src="/products/kze-b.webp" /></div><div><p className="eyebrow-red text-xs font-bold tracking-[.16em]">FÁBRICA / CHINA / 360</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] md:text-5xl">Conheça o contexto por trás das conexões.</h2><p className="mt-5 max-w-xl leading-7 text-white/65">A visita 360 existente segue acessível como uma aproximação visual ao ambiente de fábrica.</p><Link className="signal-button mt-7" href="/fabrica">Explorar fábrica 360 →</Link></div></Container></section>
      <section><Container className="py-16 md:py-24"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow-red text-xs font-bold tracking-[.16em]">PRODUTOS EM DESTAQUE</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] md:text-5xl">Séries para consulta.</h2></div><Link className="text-sm font-semibold text-white hover:text-red-300" href="/produtos">Todos os produtos →</Link></div><div className="mt-9 grid gap-5 md:grid-cols-3">{products.slice(0, 3).map((product) => <ProductCard key={product.slug} product={product} />)}</div></Container></section>
      <section className="border-t border-white/10 bg-signal-red"><Container className="flex flex-wrap items-center justify-between gap-6 py-10"><div><p className="text-xs font-bold tracking-[.16em] text-white/75">ATENDIMENTO COMERCIAL</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.04em]">Precisa localizar uma série?</h2></div><Link className="bg-white px-5 py-3 text-sm font-bold text-graphite hover:bg-graphite hover:text-white" href="/contato">Falar com especialista →</Link></Container></section>
    </div>
  </PublicShell>;
}
