// Gerado por tools/build-product-details.py — subfamília de cada produto no site atual da LSQ.
export const productSubfamilies: Record<string, string> = {
 "engate-rapido-manual-de-refrigeracao-tipo-valvula-giratoria": "Prensa Rotativa e Alça",
 "gas-rapido-montagem-da-serie-da-pistola": "Pistolas de Conexão Rápido a Gás",
 "khb-valvula-de-esfera-de-2-vias": "Válvula de esfera hidráulica bidirecional",
 "khb3k-valvula-de-esfera-de-tres-vias": "Válvula de esfera hidráulica de três vias",
 "kj-engate-rapido-hidraulico-tipo-fechado": "Engates para Hidráulica",
 "kz1-2-3-engate-de-refrigeracao-tipo-bracadeira": "Tipo Abraçadeira",
 "kzd-2-engate-rapido-hidraulico-e-pneumatico": "Engates ISO 7241-B",
 "kzd-engate-rapido-hidraulico-e-pneumatico-iso-7241-b": "Engates ISO 7241-B",
 "kze-b-engate-rapido-hidraulico-tipo-fechado": "Engates BRS HPA 14540",
 "kze-ba-engate-rapido-hidraulico-com-rosca": "Conexões Rosqueadas BRS",
 "kze-bc-engate-rapido-hidraulico": "Engates Rápido com Porca Borboleta",
 "kze-bd-engate-rapido-hidraulico-com-rosca": "Conexões Rosqueadas BRS",
 "kze-be-engate-rapido-hidraulico-com-rosca": "Conexões Rosqueadas BRS",
 "kze-engate-rapido-hidraulico-tipo-fechado": "Engates para Hidráulica",
 "kzf-engate-rapido-hidraulico-tipo-fechado-iso-7241-b": "Engates ISO 7241-B",
 "l-acelerador-bidirecional": "Acelerador bidirecional",
 "la-acelerador-com-valvula-de-retencao": "Acelerador com válvula de retenção",
 "lam-engate-rapido-de-desligamento-unico-tipo-americano": "Outros Engates Rápidos",
 "lao-engate-rapido-tipo-monomanual-e-semiautomatica": "Outros Engates Rápidos",
 "lkji-engate-rapido-de-super-alta-pressao": "Engates para Hidráulica",
 "lsq-1141-engate-rapido-hidraulico-com-rosca": "Conexões Rosqueadas BRS",
 "lsq-17-engate-rapido-pneumatico-tipo-fechado": "Engates de Intercâmbio RECTUS",
 "lsq-19-engate-rapido-pneumatico-tipo-fechado": "Engates de Intercâmbio RECTUS",
 "lsq-23-engate-rapido-pneumatico-tipo-fechado": "Engates de Intercâmbio RECTUS",
 "lsq-25-engate-rapido-pneumatico-tipo-fechado": "Engates de Intercâmbio RECTUS",
 "lsq-26-engate-rapido-pneumatico-tipo-fechado": "Engates de Intercâmbio RECTUS",
 "lsq-300-engate-rapido-pneumatico": "Engates de Intercâmbio CEJN",
 "lsq-310-engate-rapido-pneumatico": "Engates de Intercâmbio CEJN",
 "lsq-315-engate-rapido-pneumatico": "Engates de Intercâmbio CEJN",
 "lsq-320-engate-rapido-pneumatico": "Engates de Intercâmbio CEJN",
 "lsq-430-engate-rapido-pneumatico": "Engates de Intercâmbio CEJN",
 "lsq-550-engate-rapido-pneumatico": "Engates de Intercâmbio CEJN",
 "lsq-a-engate-rapido-tipo-siglehanded-e-semiautomatico": "Outros Engates Rápidos",
 "lsq-aa-engate-rapido-tipo-monomanual-e-semiautomatico": "Engates de Intercâmbio NITTO",
 "lsq-ab-acoplamento-rapido-tipo-semiautomatico-e-de-mao-unica1": "Engates de Intercâmbio NITTO",
 "lsq-an-engate-rapido-semiautimatico-tipo-botao-de-pressao": "Engates para Hidráulica",
 "lsq-c-engate-rapido-pneumatico-de-desligamento-unico": "Engates de Intercâmbio NITTO",
 "lsq-cc-engate-rapido-pneumatico-tipo-fechado": "Engates para Navios/Soldagem",
 "lsq-cc20-engate-rapido-hidraulico-tipo-fechado": "Engates para Navios/Soldagem",
 "lsq-cc50-engate-rapido-pneumatico-tipo-fechado": "Engates para Navios/Soldagem",
 "lsq-cv-valvula-de-retencao-hidraulica": "Valvula de Retenção Hidráulica",
 "lsq-dd-engate-rapido-pneumatico-tipo-fechado": "Engates para Navios/Soldagem",
 "lsq-dg-engate-rapido-tipo-monomanual-e-semiautomatico": "Outros Engates Rápidos",
 "lsq-dl-dld-multi-engates": "Multi Engates",
 "lsq-ff-engate-rapido-hidraulico-iso-16028": "Engates BRS FIRG / FACE PLANA 16028",
 "lsq-ffy-engate-rapido-hidraulico-iso-16028": "Engates BRS FIRG / FACE PLANA 16028",
 "lsq-hdb-valvula-modular": "Multi Engates",
 "lsq-hx-engate-rapido-pneumatico-tipo-valvula-de-bloqueio": "Engates para Navios/Soldagem",
 "lsq-irn-engate-rapido-hidraulico-tipo-fechado": "Engates para Hidráulica",
 "lsq-isoa-engate-rapido-hidraulico-tipo-fechado-iso-7241-a": "Engates ISO 7241-A",
 "lsq-k-engate-rapido-para-molde": "Engates para Moldes",
 "lsq-nzk1-2-3-ampliacao-interna": "Ampliação Interna",
 "lsq-pcvb1-2-3-engate-rapido-sob-pressao-tipo-ajustavel": "Tipo Ajustável",
 "lsq-pd-engate-rapido-hidraulico-tipo-fechado-novo": "BRS para diagnóstico",
 "lsq-pk-engate-rapido-hidraulico-tipo-fechado-iso-5675": "Engates BRS ISO 5675",
 "lsq-ptf-engate-rapido-hidraulico-iso-16028": "Engates BRS FIRG / FACE PLANA 16028",
 "lsq-ptr-engate-rapido-hidraulico-tipo-face-plana": "Engates para Hidráulica",
 "lsq-q1-engate-rapido-para-molde-pequeno": "Engates para Moldes",
 "lsq-q2-engate-rapido-para-molde": "Engates para Moldes",
 "lsq-q3-engate-rapido-para-molde": "Engates para Moldes",
 "lsq-rd-engate-rapido-hidraulico-tipo-japones": "Engates sem Válvula",
 "lsq-rk-engate-rapido-hidraulico-com-rosca": "Conexões Rosqueadas BRS",
 "lsq-s1-engate-rapido-hidraulico-tipo-fechado-iso-7241-a": "Engates ISO 7241-A",
 "lsq-s1-ss-engate-rapido-hidraulico-tipo-fechado-iso-7241-a": "Engates ISO 7241-A",
 "lsq-s10-engate-rapido-hidraulico-tipo-fechado": "Engates para Hidráulica",
 "lsq-s2-engate-rapido-hidraulico-tipo-fechado-iso-7241-b": "Engates ISO 7241-B",
 "lsq-s2-ss-engate-rapido-hidraulico-tipo-fechado-iso-7241-b": "Engates ISO 7241-B",
 "lsq-s3-engate-rapido-hidraulico-tipo-fechado-iso-7241-a": "Engates ISO 7241-A",
 "lsq-s4-engate-rapido-hidraulico-tipo-valvula-de-esfera-iso-5675": "Engates BRS ISO 5675",
 "lsq-s5-lsq-s5c-engate-rapido-hidraulico-tipo-push-pull-iso-5675": "Engates BRS ISO 5675",
 "lsq-s6-engate-rapido-hidraulico-tipo-fechado-iso-7241-a": "Engates ISO 7241-A",
 "lsq-s7-engate-rapido-hidraulico-tipo-fechado": "Engates para Hidráulica",
 "lsq-s8-engate-rapido-hidraulico-e-pneumatico-iso-7241-b": "Engates ISO 7241-B",
 "lsq-s9-engate-rapido-hidraulico-tipo-fechado": "Engates para Hidráulica",
 "lsq-tc-engate-rapido-hidraulico-de-alta-pressao-tipo-fechado": "Engates de Alta Pressão",
 "lsq-te-engate-rapido-hidraulico-de-alta-pressao-tipo-fechado": "Engates de Alta Pressão",
 "lsq-tf-engate-rapido-hidraulico-de-alta-pressao": "Engates de Alta Pressão",
 "lsq-tg-engate-rapido-hidraulico-tipo-fechado-iso-7241-a": "Engates ISO 7241-A",
 "lsq-tm-engate-rapido-hidraulico-tipo-fechado": "Engates para Hidráulica",
 "lsq-tnv-engate-rapido-hidraulico-tipo-fechado": "Engates para Hidráulica",
 "lsq-vep-engate-rapido-hidraulico": "Engates BRS VEP",
 "lst-engate-rapido-hidraulico-tipo-americano": "Engates sem Válvula",
 "nzkd1-2-3-engate-de-refrigeracao-de-alta-estanqueidade": "Ampliação Interna e Externa",
 "pcv-japones-fck-italiano-zzp-u-k-engate-rapido": "Engates para Hidráulica",
 "protetor-metalico-para-engates-rapidos-da-serie-lsq-s10": "Plugues para Engates Rápidos",
 "protetor-metalico-para-engates-rapidos-da-serie-lsq-s5": "Plugues para Engates Rápidos",
 "q-zb275-77-engate-rapido-hidraulico-tipo-fechado": "Engates para Hidráulica",
 "qkd-t-engate-rapido-pneumatico": "Outros Engates Rápidos",
 "qkd-x-mini-engate-rapido-pneumatico-tipo-monomanual-semiautomatico": "Outros Engates Rápidos",
 "qkd-z-engate-rapido-pneumatico-tipo-monomanual-e-semiautomatica": "Outros Engates Rápidos",
 "qkd153-engate-rapido-pneumatico": "Outros Engates Rápidos",
 "qkd156-engate-rapido-pneumatico-de-desligamento-unico": "Outros Engates Rápidos",
 "qkd158-engate-rapido-pneumatico-de-desligamento-unico": "Outros Engates Rápidos",
 "serie-da-valvula-de-enchimento-rapido": "Válvulas de Enchimento Rápido",
 "tampa-de-plastico-contra-poeira-e-plugue-para-engates-rapidos-da-serie-kze-b": "Plugues para Engates Rápidos",
 "tampa-de-plastico-contra-poeira-e-plugue-para-engates-rapidos-da-serie-lsq-ff": "Plugues para Engates Rápidos",
 "tampa-de-plastico-contra-poeira-e-plugue-para-engates-rapidos-da-serie-lsq-s1": "Plugues para Engates Rápidos",
 "tampa-de-plastico-contra-poeira-e-plugue-para-engates-rapidos-da-serie-lsq-s2": "Plugues para Engates Rápidos",
 "tampa-de-plastico-contra-poeira-e-plugue-para-engates-rapidos-da-serie-lsq-s4": "Plugues para Engates Rápidos",
 "tampa-de-plastico-contra-poeira-e-plugue-para-engates-rapidos-da-serie-lsq-s5": "Plugues para Engates Rápidos",
 "tampa-de-plastico-contra-poeira-e-plugue-para-engates-rapidos-da-serie-lsq-tf": "Plugues para Engates Rápidos",
 "tampa-de-plastico-contra-poeira-para-engates-rapidos-da-serie-lsq-pd": "Plugues para Engates Rápidos",
 "tampa-metalica-contra-poeira-e-plugue-para-engates-rapidos-da-serie-kze-b": "Plugues para Engates Rápidos",
 "tampa-metalica-contra-poeira-e-plugue-para-engates-rapidos-da-serie-kze-ba": "Plugues para Engates Rápidos",
 "tampa-metalica-contra-poeira-e-plugue-para-engates-rapidos-da-serie-kze-bc": "Plugues para Engates Rápidos",
 "tampa-metalica-contra-poeira-e-plugue-para-engates-rapidos-da-serie-lsq-vep": "Plugues para Engates Rápidos",
 "tpl-engate-rapido-hidraulico-direto": "Engates sem Válvula",
 "vbpde-echadura-hidraulica-dupla-face": "Fechadura hidráulica dupla face",
 "vbpse-fechadura-hidraulica-unilateral": "Bloqueio hidráulico unilateral"
};
